import Head from 'next/head'
import Image from 'next/image'
import Intro from '../components/Intro'
import Services from '../components/Services'
import styles from '../styles/Home.module.css'
import {data} from "../data"
import Testinomails from '../components/Testinomails'
export default function Home({Ser}) {
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Onward Tech</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.box}>
        <Intro></Intro>
        <Services Daata={Ser}></Services>   
        <Testinomails></Testinomails>     
      </main>
      
    </div>
  )
}

export const getStaticProps = async () =>{
  const Ser = data;
  return{
    props : {Ser },
};
}